



all: tst1 tst2 tst3 tst4

tst4: tst4.cpp
	g++ -O3 -o tst4 tst4.cpp

tst3: tst3.cpp
	g++ -O3 -o tst3 tst3.cpp


tst2: tst2_chickenwire.cpp
	g++ -O3 -o tst2 tst2_chickenwire.cpp


tst1: tst1.cpp
	g++ -O3 -o tst1 tst1.cpp

